spring:
  application:
    name: yupo-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxxxx:3306/yupao
    username: root
    password:
  # session 失效时间（分钟  也就是86400分钟 两个月）
  session:
    timeout: 86400
    store-type: redis #默认是none也就是单台服务器

  redis:
    port: 6379
    host:
    password: 123456
    database: 1  #默认是0
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
  profiles:
    active: dev
server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domian: loc alhost

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
